import Vue from 'vue';

import CaButton from './Ca-Button.vue';
import CaInput from './Ca-Input.vue';
import CaTextarea from './Ca-Textarea.vue';
import CaInputButton from './Ca-InputButton.vue';
import CaTag from './Ca-Tag.vue';
import CaCheckBox from './Ca-CheckBox.vue';
import CaCheckBoxList from './Ca-CheckBoxList.vue';
import CaRadioList from './Ca-RadioList.vue';
import CaModal from './Ca-Modal.vue';
import CaModalViewHeader from './Ca-ModalViewHeader.vue';
import CaModalViewBody from './Ca-ModalViewBody.vue';
import CaModalScroll from './Ca-ModalScroll.vue';
import CaModalBody from './Ca-ModalBody.vue';
import CaModalView from './Ca-ModalView.vue';
import CaModalSideMenu from './Ca-ModalSideMenu.vue';
import CaPulldown from './Ca-Pulldown.vue';
import CaFloat from './Ca-Float.vue';
import CaIcon from './Ca-Icon.vue';
import CaSwitch from './Ca-Switch.vue';
import CaDrumroll from './Ca-Drumroll.vue';
import CaBadge from './Ca-Badge.vue';
import CaSpinner from './Ca-Spinner.vue';
import CaToast from './Ca-Toast.vue';

Vue.component('CaSpinner', CaSpinner);
Vue.component('CaButton', CaButton);
Vue.component('CaInput', CaInput);
Vue.component('CaTextarea', CaTextarea);
Vue.component('CaInputButton', CaInputButton);
Vue.component('CaTag', CaTag);
Vue.component('CaCheckBox', CaCheckBox);
Vue.component('CaCheckBoxList', CaCheckBoxList);
Vue.component('CaRadioList', CaRadioList);
Vue.component('CaModal', CaModal);
Vue.component('CaModalSideMenu', CaModalSideMenu);
Vue.component('CaModalViewHeader', CaModalViewHeader);
Vue.component('CaModalViewBody', CaModalViewBody);
Vue.component('CaModalScroll', CaModalScroll);
Vue.component('CaModalBody', CaModalBody);
Vue.component('CaModalView', CaModalView);
Vue.component('CaPulldown', CaPulldown);
Vue.component('CaFloat', CaFloat);
Vue.component('CaIcon', CaIcon);
Vue.component('CaSwitch', CaSwitch);
Vue.component('CaDrumroll', CaDrumroll);
Vue.component('CaBadge', CaBadge);
Vue.component('CaToast', CaToast);
