import Vue from 'vue';

import CaButton from '../components/Ca-Button.vue';
import CaInput from '../components/Ca-Input.vue';
import CaTextarea from '../components/Ca-Textarea.vue';
import CaInputButton from '../components/Ca-InputButton.vue';
import CaTag from '../components/Ca-Tag.vue';
import CaCheckBox from '../components/Ca-CheckBox.vue';
import CaCheckBoxList from '../components/Ca-CheckBoxList.vue';
import CaRadioList from '../components/Ca-RadioList.vue';
import CaModal from '../components/Ca-Modal.vue';
import CaModalBody from '../components/Ca-ModalBody.vue';
import CaModalView from '../components/Ca-ModalView.vue';
import CaPulldown from '../components/Ca-Pulldown.vue';
import CaFloat from '../components/Ca-Float.vue';
import CaIcon from '../components/Ca-Icon.vue';
import CaSwitch from '../components/Ca-Switch.vue';
import CaDrumroll from '../components/Ca-Drumroll.vue';
import CaBadge from '../components/Ca-Badge.vue';
import CaSpinner from '../components/Ca-Spinner.vue';

Vue.component('CaSpinner', CaSpinner);
Vue.component('CaButton', CaButton);
Vue.component('CaInput', CaInput);
Vue.component('CaTextarea', CaTextarea);
Vue.component('CaInputButton', CaInputButton);
Vue.component('CaTag', CaTag);
Vue.component('CaCheckBox', CaCheckBox);
Vue.component('CaCheckBoxList', CaCheckBoxList);
Vue.component('CaRadioList', CaRadioList);
Vue.component('CaModal', CaModal);
Vue.component('CaModalBody', CaModalBody);
Vue.component('CaModalView', CaModalView);
Vue.component('CaPulldown', CaPulldown);
Vue.component('CaFloat', CaFloat);
Vue.component('CaIcon', CaIcon);
Vue.component('CaSwitch', CaSwitch);
Vue.component('CaDrumroll', CaDrumroll);
Vue.component('CaBadge', CaBadge);
