name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build-storybook
      - name: Archive storybook artifacts
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs
